version: "3.8"
services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./infra/postgres_data:/var/lib/postgresql/data
      # - ./infra/init.sql:/docker-entrypoint-initdb.d/init.sql
