name: Pylint

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'migrations/**'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'migrations/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py' ':!:docs/**' ':!:tests/**' ':!:migrations/**') > pylint-report.txt || true
    - name: Upload Pylint Report
      uses: actions/upload-artifact@v3
      with:
        name: pylint-report
        path: pylint-report.txt
    - name: Comment on Pull Request
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        script: |
          const fs = require('fs');
          const report = fs.readFileSync('pylint-report.txt', 'utf8');
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: `Pylint Report:\n\`\`\`\n${report}\n\`\`\``
          });
